name: New flow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: 
      name: PROD
      url: https://github.com/rasmus-2c/env-test/settings/environments/2835198370/edit

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Run Python script
      run: python print.py
      env:
        VAR1: ${{ vars.ARG1 }}
        VAR2: ${{ vars.ARG2 }}
        VAR3: ${{ vars.ARG3 }}

