name: Tester
on:
  workflow_dispatch:

jobs:
  greet:
    environment: Prod
    runs-on: ubuntu-latest
    env:
      ARG2: ${{ secrets.ARG2 }}
      ARG3: ${{ secrets.ARG3 }}
      ARG4: ${{ secrets.ARG4 }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Run Python Script
        run: python print.py ${{ env.ARG2 }} ${{ env.ARG3 }} ${{ env.ARG4 }}

