name: Print variables (DEV)
on:
  workflow_dispatch:

jobs:
  greet:
    environment: DEV
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Python Script
        run: python print.py "${{ vars.ARG1 }}" "${{ vars.ARG2 }}" "${{ vars.ARG3 }}"
